[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.format]
max-line-length = 100

[tool.isort]
profile = 'black'

[tool.black]
line-length = 100